// キメサイカードリスト
window.ACG_REQUIRED_CARDS = [
  { id: "ACG-136", name: "群泳カジキ", required: 4 },
  { id: "ACG-137", name: "反射石", required: 3 },
  { id: "ACG-138", name: "亜音速カジキ", required: 1 },
  { id: "ACG-139", name: "命削りの運び屋", required: 4 },
  { id: "ACG-140", name: "火速足袋", required: 2 },
  { id: "ACG-141", name: "希望漁り", required: 1 },
  { id: "ACG-142", name: "断崖を背に", required: 1 },
  { id: "ACG-143", name: "泥の像", required: 2 },
  { id: "ACG-144", name: "獅子舞行軍", required: 1 },
  { id: "ACG-145", name: "交互の湯浴み", required: 2 },
  { id: "ACG-146", name: "道標", required: 1 },
  { id: "ACG-147", name: "運命の帰郷", required: 1 },
  { id: "ACG-148", name: "暗がりの保管庫", required: 3 },
  { id: "ACG-149", name: "等価な検閲網", required: 2 },
  { id: "ACG-150", name: "臨終の咆哮", required: 1 },
  { id: "ACG-151", name: "言伝", required: 3 },
  { id: "ACG-152", name: "脱獄", required: 1 },
  { id: "ACG-153", name: "救援物資", required: 3 },
  { id: "ACG-154", name: "袋小路の捨て犬", required: 3 },
  { id: "ACG-155", name: "猫又", required: 2 },
  { id: "ACG-156", name: "テングザル", required: 4 },
  { id: "ACG-157", name: "玩具の申し子", required: 2 },
  { id: "ACG-158", name: "明日色のカメレオン", required: 4 },
  { id: "ACG-159", name: "鉄洗いグマ", required: 3 },
  { id: "ACG-160", name: "鉄クズ", required: 4 },
  { id: "ACG-161", name: "鉄鴉", required: 1 },
  { id: "ACG-162", name: "カメレオンの永地", required: 4 },
  { id: "ACG-163", name: "此岸色のカメレオン", required: 1 },
  { id: "ACG-164", name: "彼岸色のカメレオン", required: 1 }
];
